const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.AB_PLAYWRIGHT_PATH || 'playwright');
const E=require('../dist/engine.js');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts');
fs.mkdirSync(out,{recursive:true});
const report={checks:[],errors:[],requests:[],performance:{}};
const ok=(name,condition=true)=>{assert.ok(condition,name);report.checks.push(name);};
const url=process.env.AB_PREVIEW_URL || 'http://127.0.0.1:4178';
const readCount=async(page,key)=>Number((await page.locator('[data-count="'+key+'"] .stat-num').innerText()).replaceAll(',',''));
const expectCount=async(page,key,value)=>{await page.waitForFunction(({key,value})=>Number(document.querySelector('[data-count="'+key+'"] .stat-num')?.textContent.replaceAll(',',''))===value,{key,value});};
async function importTask(page,mode,raw,filtered){
  await page.locator('#newTask').click();
  await page.locator('[data-input="'+mode+'"]').click();
  if(raw)await page.locator('#rawFile').setInputFiles(raw);
  if(filtered)await page.locator('#filteredFile').setInputFiles(filtered);
  await page.locator('#analyzeBtn').click();
  await page.locator('#workspace').waitFor({state:'visible',timeout:90000});
}
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.AB_BROWSER || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
  const context=await browser.newContext({viewport:{width:1440,height:1080},acceptDownloads:true});
  const page=await context.newPage();
  page.on('pageerror',e=>report.errors.push(e.message));
  page.on('console',e=>{if(e.type()==='error')report.errors.push(e.text());});
  page.on('request',r=>report.requests.push({url:r.url(),method:r.method()}));
  page.setDefaultTimeout(12000);
  try {
    await page.goto(url);
    await page.locator('#welcome').waitFor({state:'visible'});
    ok('Initial page offers real import and clearly labeled synthetic demo');
    await page.locator('#demoBtn').click();
    await expectCount(page,'gap',2);
    ok('Demo is parsed by the real worker',await readCount(page,'reorder')===2&&await readCount(page,'duplicate')===1&&await readCount(page,'collision')===1);
    ok('Sequence list defaults to HEX with decimal underneath',(await page.locator('#eventRows tr').first().innerText()).includes('0x0065')&&(await page.locator('#eventRows tr').first().innerText()).includes('DEC 101'));
    await page.locator('#sequenceBase').selectOption('dec');
    ok('Changing display base updates axis and list without changing analysis',!(await page.locator('#chart text').allTextContents()).some(v=>v.includes('0x'))&&await readCount(page,'gap')===2);
    await page.locator('#sequenceBase').selectOption('hex');
    ok('HEX axis is explicitly labeled',(await page.locator('#chart text').allTextContents()).some(v=>v.startsWith('0x')));
    await page.screenshot({path:path.join(out,'demo-desktop.png'),fullPage:true});
    if(process.env.AB_RAW_LOG&&process.env.AB_FILTER_LOG){
      await importTask(page,'pair',process.env.AB_RAW_LOG,process.env.AB_FILTER_LOG);
      await expectCount(page,'frames',399);
      ok('Real raw input: 399 valid frames and 142 final missing IDs',await readCount(page,'gap')===142);
      await page.waitForFunction(()=>document.querySelectorAll('.seq-byte-mark').length===4);
      ok('Missing sequence is separate from the real source anchors',(await page.locator('#detailTitle').innerText()).includes('0x8407')&&(await page.locator('.sequence-map').first().innerText()).includes('0x8408'));
      ok('Raw source sequence highlights target only offset 6 and 7',JSON.stringify(await page.locator('.seq-byte-mark').allTextContents())===JSON.stringify(['08','84','06','84']));
      ok('Highlighting preserves the original timestamp and complete raw text',(await page.locator('.raw-section').first().locator('.code-line.highlight code').innerText())===fs.readFileSync(process.env.AB_RAW_LOG,'utf8').split(/\r?\n/)[7]);
      ok('Visible sequence anchors retain the unscrolled AB frame prefix',await page.locator('.raw-section .code').first().evaluate(el=>el.scrollLeft===0));
      await page.screenshot({path:path.join(out,'sample-raw.png'),fullPage:true});
      await page.locator('#search').fill('33945');
      await page.waitForFunction(()=>document.querySelector('#detailTitle').textContent.includes('同号不同内容'));
      ok('Same-ID differing-content links both L302 and L304',(await page.locator('#codeSections').innerText()).includes('L302')&&(await page.locator('#codeSections').innerText()).includes('L304'));
      ok('Collision shows the 0x8499 / 33945 / 99 84 correspondence',(await page.locator('.sequence-map').first().innerText()).includes('99 84')&&(await page.locator('#detailTitle').innerText()).includes('0x8499'));
      await page.locator('[data-locate-byte="1:7"]').click();
      ok('Clicking a header byte focuses its exact position in original text',await page.evaluate(()=>document.activeElement?.dataset.sourceByte==='1:7'));
      await page.locator('.inspector').screenshot({path:path.join(out,'sequence-anchor-detail.png')});
      await page.locator('#search').fill('');
      await page.locator('#kindFilter').selectOption('duplicate');
      await page.locator('#empty').waitFor({state:'visible'});
      ok('Empty filter does not fabricate duplicates or retain stale details',(await page.locator('#detailTitle').innerText()).includes('没有'));
      await page.locator('[data-mode="filtered"]').click();
      await expectCount(page,'frames',231);
      ok('Filtered input retains independent 54 missing IDs',await readCount(page,'gap')===54);
      await page.locator('[data-mode="pair"]').click();
      await expectCount(page,'matched',231);
      ok('Pair shows occurrence-aware 168 raw-only and zero filtered-only',await readCount(page,'rawOnly')===168&&await readCount(page,'filteredOnly')===0);
      await page.locator('#fullBtn').click();
      await page.waitForFunction(()=>document.querySelector('#chartSubtitle').textContent.includes('399'));
      await page.screenshot({path:path.join(out,'sample-pair.png'),fullPage:true});
      await page.locator('#moreFilter').click();await page.locator('#coverageFilter').selectOption('inside');
      await page.waitForFunction(()=>document.querySelector('#resultCount').textContent==='1 条');
      ok('Coverage filter isolates one in-range difference');
      await page.locator('#exportBtn').click();
      await page.locator('#exportRange').selectOption('filtered');
      const download1=page.waitForEvent('download'); await page.locator('#csvBtn').click(); const d1=await download1;
      const csvPath=path.join(out,'filtered.csv');await d1.saveAs(csvPath);
      const csv=fs.readFileSync(csvPath);
      ok('Filtered CSV download has BOM, Chinese header and one event',csv.subarray(0,3).equals(Buffer.from([239,187,191]))&&csv.toString().split('\r\n').filter(Boolean).length===2);
      ok('CSV exports the added HEX and original byte columns',csv.toString().includes('消息序号HEX')&&csv.toString().includes('序号原始字节LE'));
      await page.locator('#exportRange').selectOption('all');
      const download2=page.waitForEvent('download');await page.locator('#csvBtn').click();const d2=await download2;await d2.saveAs(path.join(out,'all.csv'));
      ok('Default all-results export includes both independent analyses and pair differences',fs.readFileSync(path.join(out,'all.csv'),'utf8').split('\r\n').filter(Boolean).length===251);
      const download3=page.waitForEvent('download');await page.locator('#txtBtn').click();const d3=await download3;await d3.saveAs(path.join(out,'all-context.txt'));
      const text=fs.readFileSync(path.join(out,'all-context.txt'),'utf8');
      ok('TXT includes event IDs and both original filenames',text.includes('[R00001]')&&text.includes('[F00001]')&&text.includes('[P00001]')&&text.includes('abBle_260413_145449.txt')&&text.includes('L302'));
      await page.locator('#exportDialog [data-close]').click();
      await page.locator('#resetFilter').click();
      await page.locator('#kindFilter').selectOption('matched');
      await page.waitForFunction(()=>document.querySelector('#resultCount').textContent==='231 条');
      ok('Matched frame view shows both source contexts',(await page.locator('#codeSections .code-name').count())===2);
      await page.locator('#kindFilter').selectOption('all');
      await page.waitForFunction(()=>document.querySelector('#resultCount').textContent==='168 条');
      await page.locator('#pageNext').click();
      await page.waitForFunction(()=>document.querySelector('#pageInfo').textContent==='2 / 3');
      ok('Results are paginated for large logs',await page.locator('#eventRows tr').count()===60);
      await page.locator('#eventRows tr').first().focus();await page.keyboard.press('Enter');
      ok('Result selection is keyboard accessible');
      await page.locator('[data-mode="raw"]').click();
      await expectCount(page,'frames',399);
      await page.locator('#chart [data-chart-id]').first().focus();await page.keyboard.press('Enter');
      ok('Chart anomaly markers support keyboard activation');
    }
    await context.setOffline(true);
    const fa=E.makeFrame(33796),fb=E.makeFrame(33798);
    const fragmented=1800000000000+','+fa.slice(0,14)+'\nerror fragment\n'+1800000000001+','+fa.slice(14)+fb;
    await importTask(page,'raw',{name:'fragment-anchors.txt',mimeType:'text/plain',buffer:Buffer.from(fragmented)});
    await expectCount(page,'frames',2);
    ok('Split fields and multiple frames per line keep accurate original highlights',JSON.stringify(await page.locator('.seq-byte-mark').allTextContents())===JSON.stringify(['06','84','04','84']));
    await page.locator('[data-locate-byte="1:7"]').click();
    ok('Cross-line high byte locator remains usable',await page.evaluate(()=>document.activeElement?.closest('.code-line').querySelector('.ln').textContent==='3'));
    const sequence=[65534,0,65535,1,1,3];
    const body=sequence.map((sid,i)=>(1800000000000+i)+','+E.makeFrame(sid)).join('\n');
    await importTask(page,'filtered',null,{name:'wrap-utf16.txt',mimeType:'text/plain',buffer:Buffer.concat([Buffer.from([255,254]),Buffer.from(body,'utf16le')])});
    await expectCount(page,'frames',6);
    ok('Standalone filtered import handles UTF-16, wrap, late and duplicate',await readCount(page,'gap')===1&&await readCount(page,'reorder')===1&&await readCount(page,'duplicate')===1);
    ok('Loaded page imports and analyzes while network is offline');
    await context.setOffline(false);
    await page.locator('#fullBtn').click();
    await page.waitForFunction(()=>document.querySelector('#chart').innerHTML.includes('正常回绕'));
    ok('Normal wrap is marked on the sequence chart');
    const xss='\nerror <img src="https://invalid.example/x" onerror="window.xss=1">\n1800000000000,'+E.makeFrame(100)+'\n1800000000001,'+E.makeFrame(102);
    await importTask(page,'raw',{name:'<img src=x onerror=alert(1)>.txt',mimeType:'text/plain',buffer:Buffer.from(xss)});
    await expectCount(page,'frames',2);
    ok('Untrusted filenames and raw lines display as inert text',await page.evaluate(()=>!window.xss&&document.querySelectorAll('#codeSections img').length===0));
    for(const width of [1280,390]){
      await page.setViewportSize({width,height:960});
      ok('No page-wide horizontal overflow at '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
      await page.screenshot({path:path.join(out,'responsive-'+width+'.png'),fullPage:true});
    }
    await page.setViewportSize({width:1440,height:1080});
    const large=path.join(out,'generated-50MiB.txt'),recordBytes=223,recordCount=Math.ceil(50*1048576/recordBytes);
    const fd=fs.openSync(large,'w');let chunk='';
    const payload=[0x7b,93,0x12,...Array.from({length:93},(_,i)=>(i*3+4)&255)];
    const header=E.makeFrame(0,payload);
    for(let i=0;i<recordCount;i++){
      const sid=i&65535;
      const h=header.slice(0,12)+Buffer.from([sid&255,sid>>>8]).toString('hex')+header.slice(16);
      chunk+=(1800000000000+i)+','+h+'\n';
      if(chunk.length>1048576){fs.writeSync(fd,chunk);chunk='';}
    }
    if(chunk)fs.writeSync(fd,chunk);fs.closeSync(fd);
    report.performance.fileBytes=fs.statSync(large).size;report.performance.frames=recordCount;
    await page.evaluate(()=>{window.tickCount=0;window.maxTickDelay=0;let previous=performance.now();window.tickTimer=setInterval(()=>{const now=performance.now();window.maxTickDelay=Math.max(window.maxTickDelay,now-previous);previous=now;window.tickCount++;},50);});
    const started=Date.now();await importTask(page,'raw',large);await expectCount(page,'frames',recordCount);
    report.performance.elapsedMs=Date.now()-started;
    report.performance.ui=await page.evaluate(()=>{clearInterval(window.tickTimer);return{ticks:window.tickCount,maxTickDelayMs:window.maxTickDelay};});
    ok('50 MiB multi-cycle file analyzed without false anomalies',await readCount(page,'gap')===0&&await readCount(page,'duplicate')===0&&await readCount(page,'reorder')===0);
    ok('UI remains responsive while worker parses 50 MiB',report.performance.ui.ticks>3&&report.performance.ui.maxTickDelayMs<1500);
    await page.screenshot({path:path.join(out,'large-log.png'),fullPage:true});
    const pairStarted=Date.now();
    await importTask(page,'pair',large,large);
    await page.locator('[data-mode="pair"]').click();
    await expectCount(page,'matched',recordCount);
    report.performance.pairElapsedMs=Date.now()-pairStarted;
    ok('Two 50 MiB files pair without false differences',await readCount(page,'rawOnly')===0&&await readCount(page,'filteredOnly')===0&&await readCount(page,'pairOrder')===0);
    await page.locator('#kindFilter').selectOption('matched');
    await page.waitForFunction(n=>document.querySelector('#resultCount').textContent===n.toLocaleString('zh-CN')+' 条',recordCount);
    ok('Large matched view stays paginated',await page.locator('#eventRows tr').count()===60);
    await page.locator('#newTask').click();await page.locator('#rawFile').setInputFiles(large);await page.locator('#analyzeBtn').click();
    await page.locator('#progressDialog').waitFor({state:'visible'});
    const cancelAt=Date.now();await page.locator('#cancelAnalysis').click();await page.locator('#welcome').waitFor({state:'visible'});
    report.performance.cancelMs=Date.now()-cancelAt;
    ok('Cancel terminates analysis and disables final result export',await page.locator('#exportBtn').isDisabled());
    await page.locator('#demoBtn').click();await expectCount(page,'frames',10);
    await page.locator('#toast').evaluate(el=>el.hidden=true);
    await page.screenshot({path:path.join(out,'demo-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:900});
    await page.screenshot({path:path.join(out,'demo-mobile.png'),fullPage:true});
    ok('New analysis works after cancellation');
    // The production assets also work from an unzipped local folder; hosting uses the same files.
    const local=await context.newPage();
    local.on('pageerror',e=>report.errors.push(e.message));
    await local.goto(pathToFileURL(path.join(root,'dist/index.html')).href);
    await local.locator('#demoBtn').click();await expectCount(local,'frames',10);
    ok('Local file preview runs real worker with the same static assets');
    await local.close();
    ok('No unexpected browser errors',report.errors.length===0);
    ok('No log uploads or third-party requests',report.requests.every(r=>r.method==='GET'&&(/^(http:\/\/127\.0\.0\.1:4178|file:|blob:)/.test(r.url))));
    report.browser=await browser.version();report.success=true;
    console.log(JSON.stringify({passed:report.checks.length,performance:report.performance,browser:report.browser},null,2));
  } finally {
    fs.writeFileSync(path.join(out,'browser-verification.json'),JSON.stringify(report,null,2));
    await browser.close();
  }
})().catch(e=>{console.error(e);process.exitCode=1;});
